### PR TITLE
Added Tests and Bug fixes

### PR DESCRIPTION
**Pull request by gmottn**
Added Tests for GameSession and Queue
Also fixed the following Bugs

- TImer is now more consistent and not jittery
- Added check in welcome.html to make sure team ID is valid
- RemovePlayer function no longer removes more players then it should

### CODE REVIEW

**Comment by MichaelHalaj** [comment]
On my end, the timer still seems to speed up as more players join the game.  For example, if the timer says 30 and there are currently 3 players playing, then the timer will quickly speed through the next 3 numbers and go to 27. It appears that the timer subtracts for each player, which should not be the case.

**Comment by gmottn** [comment]
I cant seem to replicate your issue on my end. to me it all looks good. can you send a video of it happening per chance?

**Comment by MichaelHalaj** [comment]
> I cant seem to replicate your issue on my end. to me it all looks good. can you send a video of it happening per chance?
Bug - Made with Clipchamp

**Comment by gmottn** [comment]
is this only for the 30 second timer mid game, or does this happen in the 60 second start up as well?

**Comment by MichaelHalaj** [comment]
It happens in the 60 second start up as well

**Pull request closed without merging**
